name: project-opinion-dynamics-experts
channels:
  - defaults
dependencies:
  - python=3.10.8
  - matplotlib=3.5.3
  - seaborn=0.12.0
  - tqdm=4.64.1
  - ipykernel=6.15.2
  - ipywidgets=7.6.5
  - scipy=1.9.1 
  - networkx=2.6.3
  - conda-forge::powerlaw=1.4.6
